[start]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php start
parameters:
type:script
message:starting nebula

[stop]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php stop
parameters:
type:script
message:stopping nebula

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php restart
parameters:
type:script
message:restarting nebula

[reconfigure]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php apply
parameters:
type:script
message:reconfigure nebula

[status]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php status
parameters:
type:script_output
message:nebula status
