<?php

/*
 * Copyright (C) 2026 Henry Stern <henry@stern.ca>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

namespace OPNsense\Nebula;

use OPNsense\Base\BaseModel;

/**
 * Class Nebula — single-node Nebula configuration model.
 *
 * The on-appliance PHP has no yaml extension, so the config is hand-emitted.
 * The firewall block is fixed permissive for this MVP (the overlay is
 * certificate-gated); granular overlay firewalling is a later addition.
 */
class Nebula extends BaseModel
{
    public const NEBULA_DIR = '/usr/local/etc/nebula';
    public const CA_FILE = self::NEBULA_DIR . '/ca.crt';
    public const CERT_FILE = self::NEBULA_DIR . '/host.crt';
    public const KEY_FILE = self::NEBULA_DIR . '/host.key';
    public const CONFIG_FILE = self::NEBULA_DIR . '/config.yml';
    public const PID_FILE = '/var/run/nebula.pid';

    /**
     * Render the nebula config.yml for the configured node.
     */
    public function generateConfig(): string
    {
        $g = $this->general;
        $port = (int)(string)$g->listen_port;
        $amLighthouse = (string)$g->am_lighthouse === '1';

        $out = "# Generated by os-nebula. Do not edit by hand.\n";
        $out .= "pki:\n";
        $out .= '  ca: ' . self::CA_FILE . "\n";
        $out .= '  cert: ' . self::CERT_FILE . "\n";
        $out .= '  key: ' . self::KEY_FILE . "\n";

        $staticMap = $this->parseStaticHostMap((string)$g->static_host_map);
        if (!empty($staticMap)) {
            $out .= "static_host_map:\n";
            foreach ($staticMap as $nebulaIp => $targets) {
                $quoted = array_map(fn($t) => '"' . $t . '"', $targets);
                $out .= '  "' . $nebulaIp . '": [' . implode(', ', $quoted) . "]\n";
            }
        }

        $out .= "lighthouse:\n";
        $out .= '  am_lighthouse: ' . ($amLighthouse ? 'true' : 'false') . "\n";
        $hosts = $this->splitLines((string)$g->lighthouse_hosts);
        if (!empty($hosts)) {
            $out .= "  hosts:\n";
            foreach ($hosts as $host) {
                $out .= '    - "' . $host . "\"\n";
            }
        }

        $out .= "listen:\n  host: 0.0.0.0\n  port: " . $port . "\n";
        /* sane defaults: punch + respond for NAT traversal, info-level text logs */
        $out .= "punchy:\n  punch: true\n  respond: true\n";
        $out .= "logging:\n  level: info\n  format: text\n";
        $out .= "tun:\n  dev: nebula1\n";
        $out .= "firewall:\n";
        $out .= "  outbound:\n    - port: any\n      proto: any\n      host: any\n";
        $out .= "  inbound:\n    - port: any\n      proto: any\n      host: any\n";

        return $out;
    }

    /**
     * Split a textarea into a list of trimmed, non-empty lines.
     */
    private function splitLines(string $raw): array
    {
        $lines = [];
        foreach (preg_split('/\r\n|\r|\n/', $raw) as $line) {
            $line = trim($line);
            if ($line !== '') {
                $lines[] = $line;
            }
        }
        return $lines;
    }

    /**
     * Parse "nebula_ip = host:port[, host:port]" lines into a map of
     * overlay-IP => [underlay target, ...].
     */
    private function parseStaticHostMap(string $raw): array
    {
        $map = [];
        foreach ($this->splitLines($raw) as $line) {
            $eq = strpos($line, '=');
            if ($eq === false) {
                continue;
            }
            $key = trim(substr($line, 0, $eq));
            if ($key === '') {
                continue;
            }
            $targets = [];
            foreach (explode(',', substr($line, $eq + 1)) as $target) {
                $target = trim($target);
                if ($target !== '') {
                    $targets[] = $target;
                }
            }
            if (!empty($targets)) {
                $map[$key] = $targets;
            }
        }
        return $map;
    }
}
